# Generated by Django 4.1.3 on 2022-12-03 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupModel',
            new_name='CollectionModel',
        ),
    ]
