# Generated by Django 4.1.3 on 2022-12-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_instagrammodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramModel',
        ),
    ]
