# Generated by Django 4.1.3 on 2022-12-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_clothesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.AlterModelOptions(
            name='clothesmodel',
            options={'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежда'},
        ),
        migrations.AlterModelOptions(
            name='collectionmodel',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='configsmodel',
            options={'verbose_name': 'Конфигурация', 'verbose_name_plural': 'Конфигурация'},
        ),
    ]
