# Generated by Django 4.1.3 on 2022-12-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sizesmodel_alter_clothesmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesmodel',
            name='sizes',
            field=models.ManyToManyField(to='main.sizesmodel'),
        ),
    ]
