# Generated by Django 4.1.3 on 2022-12-23 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_clothesmodel_photos_photomodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodel',
            name='img',
        ),
    ]
