# Generated by Django 4.1.3 on 2022-12-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_photomodel_name_photomodel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothesmodel',
            name='sizes',
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='img',
            field=models.ImageField(upload_to='media/img/'),
        ),
        migrations.DeleteModel(
            name='SizesModel',
        ),
        migrations.AddField(
            model_name='clothesmodel',
            name='sizes',
            field=models.IntegerField(choices=[[42, 'XS XS-90-164'], [44, 'S S-94-164'], [46, 'M M-98-170'], [48, 'M M-102-170'], [50, 'L L-106-176'], [52, 'XL XL-110-176'], [54, 'XL XL-114-176']], default=0),
            preserve_default=False,
        ),
    ]
