# Generated by Django 4.1.3 on 2022-12-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_clothesmodel_sizes_alter_photomodel_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesmodel',
            name='sizes',
            field=models.JSONField(),
        ),
    ]
