# Generated by Django 4.1.3 on 2022-12-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_clothesmodel_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesmodel',
            name='sizes',
            field=models.CharField(max_length=250),
        ),
    ]
