# Generated by Django 4.1.3 on 2022-12-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_colormodel_alter_clothesmodel_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesmodel',
            name='color',
            field=models.ManyToManyField(to='main.colormodel'),
        ),
    ]
