# Generated by Django 4.1.3 on 2022-12-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_clothesmodel_article_clothesmodel_composition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSlider1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/img/')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('button_text', models.CharField(max_length=250)),
                ('button_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MainPageSlider2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='media/img/')),
                ('photo2', models.ImageField(upload_to='media/img/')),
                ('title', models.CharField(max_length=250)),
                ('description1', models.CharField(max_length=1000)),
                ('description2', models.CharField(max_length=1000)),
                ('button_text', models.CharField(max_length=250)),
                ('button_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
