# Generated by Django 4.1.3 on 2023-01-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_sizemodel_remove_clothesmodel_sizes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationOfOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
