# Generated by Django 4.1.3 on 2023-01-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_informationoforders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformationOfOrders',
            new_name='InformationOfOrdersModel',
        ),
    ]
