# Generated by Django 4.1.3 on 2023-01-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_informationoforders_informationofordersmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationofordersmodel',
            name='link',
        ),
        migrations.AddField(
            model_name='informationofordersmodel',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
